### DISCUSSION TITLE
Integration with the new media query: prefers-color-scheme

### DISCUSSION THREAD

**Discussion by YamiOdymel** [fomantic/Fomantic-UI#1022] [General] [answered]
**What is it**

The incoming media query [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) allows developers to change the styles based on the user preference about the *dark* theme or *light* theme.

```css
@media (prefers-color-scheme: dark) {
  div {
     color: white;
     background: black;
  }
}

@media (prefers-color-scheme: light) {
  div {
     color: black;
     background: white;
  }
}
```

**What should we do**

Maybe a solution, tutorial about how to adapt two different Fomantic-UI themes with the  `prefers-color-scheme` media query, or a discussion about how to support this feature.

**Similar discussion**

[【twbs/bootstrap】Support for prefers-color-scheme media query](https://github.com/twbs/bootstrap/issues/27514)

**Comment by YamiOdymel** [comment]
Since we have the new [Central dynamic color map](https://github.com/fomantic/Fomantic-UI/pull/261/), it's possible to add the color variables for the dark theme.

```diff
@pinkiepie: {
    color         : @pinkie;
+   darkColor     : @darkPinkie;
    light         : @lightPinkie;
+   darkLight     : @darkPinkie;
    background    : @lightPinkie;
+   darkBackground: @darkPinkie;
    ...
};
```

But it's stupid since you will have to render the styles twice now for the different color scheme.

```css
@media (prefers-color-scheme: light) {
  .ui.pinkiepie.button {
     color     : @color;
     background: @background;
  }
}

@media (prefers-color-scheme: dark) {
  .ui.pinkiepie.button {
     color     : @darkColor;
     background: @darkBackground;
  }
}
```

**Solution** 

The solution will be the [CSS Variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties). Where we only need to define the style once and change the variable only between the different preferred color scheme.

```css
/** 
  * Variables 
  */

@media (prefers-color-scheme: light) {
  :root {
    --pinkepieColor     : @color;
    --pinkepieBackground: @background;
  }
}

@media (prefers-color-scheme: dark) {
  :root {
    --pinkepieColor     : @darkColor;
    --pinkepieBackground: @darkBackground;
  }
}

/** 
  * Definition
  */

.ui.pinkiepie.button {
   color     : var(--pinkepieColor);
   background: var(--pinkepieBackground);
}
```
