### DISCUSSION TITLE
[build] self-hosting 'lato' font rather using google-font

### DISCUSSION THREAD

**Discussion by dutrieux** [fomantic/Fomantic-UI#1827] [General] [answered]
I try to self-hosting 'lato' font rather using google api, I do that :

- From the url : https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400%3B0,700%3B1,400%3B1,700&subset=latin&display=swap, I download all fonts :
https://fonts.gstatic.com/s/lato/v17/S6u8w4BMUTPHjxsAUi-qJCY.woff2 -> `lato_italic_400_ext.woff2`
https://fonts.gstatic.com/s/lato/v17/S6u8w4BMUTPHjxsAXC-q.woff2 ->  `lato_italic_400.woff2`
https://fonts.gstatic.com/s/lato/v17/S6u_w4BMUTPHjxsI5wq_FQft1dw.woff2 -> `lato_italic_700_ext.woff2`
https://fonts.gstatic.com/s/lato/v17/S6u_w4BMUTPHjxsI5wq_Gwft.woff2 -> `lato_italic_700.woff2`
https://fonts.gstatic.com/s/lato/v17/S6uyw4BMUTPHjxAwXjeu.woff2 -> `lato_normal_400_ext.woff2`
https://fonts.gstatic.com/s/lato/v17/S6uyw4BMUTPHjx4wXg.woff2 -> `lato_normal_400.woff2`
https://fonts.gstatic.com/s/lato/v17/S6u9w4BMUTPHh6UVSwaPGR_p.woff2 -> `lato_normal_700_ext.woff2`
https://fonts.gstatic.com/s/lato/v17/S6u9w4BMUTPHh6UVSwiPGQ.woff2 -> `lato_normal_700.woff2`

- I dowload too https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400%3B0,700%3B1,400%3B1,700&subset=latin&display=swap -> `latofonts.css`

- I put all *.woff2 to `<fomantic-ui install>\src\themes\myTheme\assets\fonts\`
- I put `latofonts.css` to `<fomantic-ui install>\src\themes\myTheme\assets\`
- I modify `latofonts.css` to change the path of all *.woff2 file like this :

```css
/* latin-ext */
@font-face {
  font-family: 'Lato';
  font-style: italic;
  font-weight: 400;
  font-display: swap;
  src: url('./themes/myTheme/assets//fonts/lato_italic_400_ext.woff2') format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Lato';
  font-style: italic;
  font-weight: 400;
  font-display: swap;
  src: url('./themes/myTheme/fonts/lato_italic_400.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
...
```
- I create new file `site.variables` in `<fomantic-ui install>\src\themes\myTheme\globals\` directory like this :
```less
/*******************************
     User Global Variables
*******************************/

@importGoogleFonts : false;
```
- create new file 'site.overrides' in `<fomantic-ui install>\src\themes\myTheme\globals\` directory like this :
```less
/*******************************
        Global Overrides
*******************************/

@import  (inline) "../assets/latofonts.css";
```
- I modify `theme.config` in `<fomantic-ui install>\src\` to change the @site element :
```less
/* Global */
@site       : 'myTheme';
```
- I build fomanticUI project :
```bash
> npx gulp build
```

~~But if a check the `semantic.css` in `dist` directory, there **isn't** the `@import url('./themes/myTheme/assets/latofonts.css')`~~

~~Maybe I missing something or it's not the good way to do that.~~
