### DISCUSSION TITLE
Ellipsis on selected item of dropdown

### DISCUSSION THREAD

**Discussion by smartm0use** [fomantic/Fomantic-UI#1883] [Modules (Modal, Dropdown, Popup, Calendar, Toast, ...)]
Hello,
I have a dropdown with items having long text and they go ahead instead of having ellipsis. And this is fine for me.
But I would like to have ellipsis on the selected item only.

This is my dropdown:

![Screenshot at 2021-02-11 16-56-07](https://user-images.githubusercontent.com/5399265/107663164-5a874300-6c8b-11eb-8381-8152341d32d9.png)

If I select an item I get this:

![Screenshot at 2021-02-11 17-00-40](https://user-images.githubusercontent.com/5399265/107663226-68d55f00-6c8b-11eb-9abe-854e17be3040.png)

Instead, I would like to have this:

![Screenshot at 2021-02-11 16-57-01](https://user-images.githubusercontent.com/5399265/107663250-71c63080-6c8b-11eb-97e2-16c15c728d51.png)

Any way to do it in a "Fomantic way" or do I need to apply to any CSS rule?

**Comment by lubber-de** [comment]
Override via

```css
/* double .ui.ui is needded to increase specificity and successfully override the settings */
.ui.ui.dropdown .menu > .item {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
```

See https://jsfiddle.net/lubber/Lbgod0zs/10/

**Comment by lubber-de** [comment]
ok, i recognized you want it only for the selected entry. There is no fomantic way, as it would also need a fixed width. You then have to adjust this yourself via css

**Reply by jamessampford** [reply]
Could probably use the callback and remove characters and update the text by looking at the width as characters are added?

Could possibly do this within the module under a flag, `trimmedSelectedText`possibly, though may need to also take into account onload/resizing, could be a good addition

**Comment by smartm0use** [comment]
Would you to set ellipsis using JS instead of CSS?

**Comment by smartm0use** [comment]
Can you help me with CSS code?

https://jsfiddle.net/cofhkugn/1/

**Comment by lubber-de** [comment]
@smartm0use 
Here you are
https://jsfiddle.net/lubber/13qa2peb/9/
```css
@media only screen and (min-width: 767.98px) {
  .ui.dropdown > .text {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    max-width: 33vw; /* This is according to your jsfiddle which uses a 3-col layout */
  }
}
```
