### DISCUSSION TITLE
uppercase text

### DISCUSSION THREAD

**Discussion by EDUARDOFERZ** [fomantic/Fomantic-UI#2291] [Elements (button, image, label, loader, ...)] [answered]
Is there code to uppercase texts]?

**Comment by lubber-de** [comment, marked as answer]
You can use CSS like this
```css
#myelement {
	text-transform: uppercase;
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
