### DISCUSSION TITLE
Sidebar

### DISCUSSION THREAD

**Discussion by fabianpallares** [fomantic/Fomantic-UI#2821] [Elements (button, image, label, loader, ...)] [answered]
Hello, how do I place the icon on the left in a sidebar control item?

Thanks and regards.

**Comment by lubber-de** [comment, marked as answer]
This is basically adjusted at compile time via LESS variables, so there currently is no separate variant to put the icon to the left.
But, if you dont want to recompile, you can revert the float for those items by

```CSS
.ui.vertical.sidebar.menu .item > i.icon {
  float: none;
  margin: 0 .35714286em 0 0;
}
```
See https://jsfiddle.net/lubber/4m2coysx/7/
