### DISCUSSION TITLE
Overriding fonts in Fomantic UI

### DISCUSSION THREAD

**Discussion by ttasovac** [fomantic/Fomantic-UI#3194] [General] [answered]
I have a Laravel project with Fomantic UI 2.9.3. I am using gulp build tools to generate `semantic.css`. I also have an offline font, called "Platforma Sans" which I want to use instead of the default Lato.

I have added:

```css
@fontName: "Platforma Sans";
```

to `semantic/src/site/globals/site.variables`

and, based on https://stackoverflow.com/a/54208399/1510260, and because I use the default theme, I have added: 

```css
@font-face {
  font-family: "Platforma Sans";
  src: url("themes/default/assets/fonts/platformasans-regular-webfont.eot");
  src: url("themes/default/assets/fonts/platformasans-regular-webfont.woff")
      format("woff"),
    url("themes/default/assets/fonts/platformasans-regular-webfont.woff2")
      format("woff2");
}
```

to `semantic/src/site/globals/site.overrides`. 

When I build using `npx gulp build`, `semantic.css` is generated, but with this:

```css
/*******************************
         Theme Overrides
*******************************/

/*******************************
         Site Overrides
*******************************/
/*!
 * # Fomantic-UI 2.9.3 - Site
 * https://github.com/fomantic/Fomantic-UI/
 *
 *
 * Released under the MIT license
 * https://opensource.org/licenses/MIT
 *
 */

/*******************************
             Page
*******************************/

@font-face {
  font-family: "Platforma Sans";
  src: url("/fonts/LatoLatin-Regular.woff2") format("woff2") , url("/fonts/LatoLatin-Regular.woff") format("woff");
  font-style: normal;
  font-weight: normal;
  font-display: swap;
  text-rendering: optimizeLegibility;
  unicode-range: U+0000, U+000D, U+0020-007E, U+00A0-017F, U+0192, U+0218-021B, U+0237, U+02C6-02C7, U+02C9, U+02D8-02DD, U+0394, U+03A9, U+03BC, U+03C0, U+1E80-1E85, U+2010, U+2013-2014, U+2018-201A, U+201C-201E, U+2020-2022, U+2026, U+2030, U+2039-203A, U+2044, U+20A3-20A4, U+20A7, U+20AC, U+2113, U+2122, U+2126, U+212E, U+2202, U+2206, U+220F, U+2211-2212, U+2215, U+2219-221A, U+221E, U+222B, U+2248, U+2260, U+2264-2265, U+25CA, U+F8FF, U+FB00-FB04;
}
```

This is wrong because "Platforma Sans" is clearly not be found at "/fonts/LatoLatin-Regular.woff2".

Does this mean that my `@fontName` from `semantic/src/site/globals/site.variables` has been picked up correctly, but that my `@font-face` from `semantic/src/site/globals/site.overrides` has been ignored? 

The only place where I could find "LatoLatn" is in `semantic/src/themes/default/globals/site.variables`, where I see:

```css
@fontName: "Lato";
@fontFileNameLatin: "LatoLatin";
@fontFileNameSupplement: "Lato";
```

and things like:

```css
@fonts: {
    @regularLatin: {
        font-family: @fontName;
        src: url("@{fontPath}/@{fontFileNameLatin}-Regular.woff2") format("woff2") if(@supportIE, e(",") url("@{fontPath}/@{fontFileNameLatin}-Regular.woff") format("woff"));
// etc.
}
```

Why is my `@font-face` instruction in  `semantic/src/site/globals/site.overrides` not overriding the `site.variables` from the default theme? And what would be the proper way of addressing this issue?

Many thanks in advance!

**Comment by lubber-de** [comment, marked as answer]
The stackoverflow article covers the old SUI way.
FUI enhanced that, so you can **entirely define your font face definition within the single `@fonts` variable inside `site.variables`** 🙂 

Btw, the path "themes/asses/fonts...." is available at compile-time only, So the /fonts/*.* path is build relative to the generated "semantic.css" file.
Just saying, you might change that path, in case the CSS is compiled as desired but the font still doesn't load
Btw2: You only need eot files if you want to support IE 6-8 (which FUI overall doesnt!), all other current browsers support at least woff... you may consider removing that separate src line

However, given your desired use case and example code you should only need to adjust the `@fonts` variable as follow
```less
/* fontname is elsewhere used as well (e.g., header) , so set it globally here, too*/
@fontName: "Platforma Sans";
@fonts: {
    @platforma: {
        font-family: @fontName;
        src: url("themes/default/assets/fonts/platformasans-regular-webfont.eot");
        src: url("themes/default/assets/fonts/platformasans-regular-webfont.woff") format("woff"), url("themes/default/assets/fonts/platformasans-regular-webfont.woff2") format("woff2");
    };
};
```
everything else found inside the `*.overrides` files will be appended to CSS, so the original font face definitions will be kept.
But, as explained above, the overrides should not be necessary anymore for your use case.

if interested, you could read my orignal PR description for that new logic at https://github.com/fomantic/Fomantic-UI/pull/2359

> I implemented a new variable @fonts which allows for a totally free description of font faces to be imported if needed. Each declared property will be used, so one can customize them as needed by that single variable.
