### DISCUSSION TITLE
Checkbox - inverted checkbox have black test when checked

### DISCUSSION THREAD

**Discussion by etshy** [fomantic/Fomantic-UI#391] [Modules (Modal, Dropdown, Popup, Calendar, Toast, ...)] [answered]
# Bug Report

## Steps to reproduce
1. Check a toggleCheckbox

## Expected result
The label stay in white

## Actual result
the label become black.

## Testcase
https://jsfiddle.net/L27zd9mg/

## Version
2.7.1

Edit : A little question at the same time, about Checkbox toggle : Is it possible to override the blue background color in the toggle ?

**Comment by lubber-de** [comment]
You have to use `ui inverted checkbox toggle`, then it works as expected
See https://jsfiddle.net/0zmvkd2a/

**Comment by lubber-de** [comment]
Overriding the blue color can be achieved by either changing `@toggleOnLaneColor` and `@toggleOnFocusLaneColor` in `checkbox.variables` and re-compile fomantic or as follows in your app

```css
.ui.inverted.toggle.checkbox input:checked ~ .box:before,
.ui.inverted.toggle.checkbox input:checked ~ label:before,
.ui.inverted.toggle.checkbox input:focus:checked ~ .box:before,
.ui.inverted.toggle.checkbox input:focus:checked ~ label:before {
    background-color: #ff0000 !important;
}
```
See: https://jsfiddle.net/0zmvkd2a/1/
