### ISSUE TITLE
[Accordion][Header] Header with content has display:none when in an accordion element

### ISSUE THREAD

**Issue by Atulin** [fomantic/Fomantic-UI#102]
### Steps

1. Create an accordion
2. In the visible part, add a header with content inside
```html
<h2 class="ui grey header">
    <i class="newspaper outline padded icon"></i>
    <div class="content">
        <span class="s-title">Top 10 anime fights</span>
        <div class="sub header s-author">By John Johnson</div>
     </div>
 </div>
```

### Expected Result

Header is visible, like it was prior to me upgrading from SUI to FUI.

### Actual Result

Header receives `display: none`:
![image](https://user-images.githubusercontent.com/11233299/45003743-c9094680-afe5-11e8-9c34-8ae09c3d6b2c.png)

### Version
2.5

### Testcase
https://jsfiddle.net/29onq46h/

**Comment by prudho** [comment]
Seems to be introduced by 1dea0bf4dd4f5f61315fe200e1cef2df2d254459.

@ColinFrick it should be fixable by changing this code:
```css
.ui.accordion .content:not(.active),
.ui.accordion .accordion .content:not(.active) {
  display: none;
}
```

With this code:
```css
.ui.accordion > .content:not(.active),
.ui.accordion .accordion > .content:not(.active) {
  display: none;
}
```

What do you think ?

**Comment by ColinFrick** [comment]
I implemented it similar to the original state with `:not(.active)`

```css
.ui.accordion .title ~ .content:not(.active),
.ui.accordion .accordion .title ~ .content:not(.active) {
  display: none;
}
```
