### ISSUE TITLE
[Dimmer] Hover Dimmer

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#1178]
# Feature Request

## Description
While text overlays were implemented [here](https://github.com/Semantic-Org/Semantic-UI/issues/3459), I think a css-only variation would be welcome so users do not have to use the transition module for a basic fading text overlay.

I also think, if implemented, it would be nice to show an example in the variations section for image, because dimmer is not the section I would have looked to find the text overlay feature.

## Example
It can pretty much be implemented with the following css:

```css
.ui.hover.dimmer {
  display: flex;
  transition: opacity .25s ease-in-out;
}

.ui:hover>.ui.hover.dimmer {
    opacity: 1;
}
```

## Testcase
https://jsfiddle.net/24by6z1r/

## Screenshot (when possible)
![Screen record from 2019-11-15 16 44 55](https://user-images.githubusercontent.com/7832163/68983274-76b9dd00-07c7-11ea-92c7-35517fd6e806.gif)
