### ISSUE TITLE
[Search] Inline Headers for Categories

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#1195]
# Feature Request

## Description
Suggested by @nk9 in Semantic-Org/Semantic-UI/issues/6901, an inline header variation for search categories would be a nice addition. This feature was created because:

> Both my category names and item titles were quite long, so stacking them next to each other resulted in a lot of wasted space.

He also figured out a way to do it completely with CSS.

## Example
[Taken from his StackOverflow question](https://stackoverflow.com/questions/58993013/how-do-i-show-semantic-ui-category-headers-as-an-item-in-the-search-results-list)
```css
.ui.category.search>.results .category {
  display: block;
  width: 100%;
}

.ui.category.search .results {
  width: 600px;
  width: 100%;
}

.ui.category.search>.results .category>.name {
  display: block;
  width: 100%;
  white-space: normal;
}

.ui.category.search>.results .category .results {
  display: block;
  width: 100%;
}

.ui.category.search>.results .category .result {
  display: block;
  width: 100%;
}

.ui.search>.results .result .description {
  width: 100%;
}
```

## Testcase
https://jsfiddle.net/45Lhyrde/

## Screenshot
![image](https://user-images.githubusercontent.com/7832163/69646200-9f8e6d80-1024-11ea-8429-faa6a9a39dfc.png)
