### ISSUE TITLE
Select width changes according to the selected item

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1246]
Hello, I have a select with some items. Some of these could be pretty long and if users select them the select become longer. And if they select again a short item the select width changes again. How can I avoid this behaviour and have select with a fixed width?

Here is my code: https://codepen.io/smartm0use_/pen/wvBPyEB

**Comment by lubber-de** [comment]
Adjust the CSS for the underlying `.text` according to your needs:
```css
.ui.fixed.dropdown .text {
  width: 150px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
See https://jsfiddle.net/4w26qvr9/
