### ISSUE TITLE
Truncate text

### ISSUE THREAD

**Issue by paddockFerrari** [fomantic/Fomantic-UI#1276]
I would like to know whether it would be possible or how logical it would be to implement a truncable option in the framework.

This truncate option, I see for example for attached labels and lists.

**Comment by lubber-de** [comment]
I think i havent exactly understood your request. A bit more explanation is needed.
Could you please provide an example ?

**Comment by paddockFerrari** [comment]
If you have something like [this](https://jsfiddle.net/Lrw71cvh/). I think it would be nice with a truncate option to have everything in one line instead of three.

**Comment by YamiOdymel** [comment]
You could easily archive that with `text-overflow` if you currently need a solution.

```css
.ui.ui.ui.red.label {
    overflow     : hidden;
    text-overflow: ellipsis;
    white-space  : nowrap;
}
```

![image](https://user-images.githubusercontent.com/7308718/72729760-f2bb1180-3bca-11ea-92d7-40a19225b861.png)
