### ISSUE TITLE
[Form] Right Aligned Button

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#1499]
# Feature Request
I regularly put action buttons on the right side of form. If I don't have any default (left aligned) buttons and only use right aligned buttons the content under the form is not cleared correctly. I normally fix it by adding the following css:

```css
.ui.clearing.form:after {
    content: "";
    display: block;
    clear: both;
}
```

I think this would make sense to add to the framework, since it's such a common pattern. Modals even use this pattern!

## Example
https://jsfiddle.net/uhtvoexc/1/

## Screenshot
![image](https://user-images.githubusercontent.com/7832163/83649877-ed0c0a00-a574-11ea-84be-824219fcbb68.png)
