### ISSUE TITLE
How can we disable the arrow that moves to previous/next month in inline calendar?

### ISSUE THREAD

**Issue by sonam1318** [fomantic/Fomantic-UI#1534]
# Help Wanted
How can we disable the arrow that moves to previous/next month in inline calendar? 

I want to disable the marked arrows in the screenshot.
![Inline_Calendar](https://user-images.githubusercontent.com/21173193/85621514-08090000-b683-11ea-8463-a47764a2e52d.png)

**Comment by lubber-de** [comment]
#### Option 1
Disable pointer events
- Buttons will still be visible...
- ...but clicking on them is ignored 

```css
.ui.calendar .prev.link,
.ui.calendar .next.link {
  pointer-events:none; 
}
```

#### Option 2
Remove the buttons
```css
.ui.calendar .prev.link,
.ui.calendar .next.link {
  display:none; 
}
```
