### ISSUE TITLE
Can @font-face about font-family: 'Icons' be made optional too?

### ISSUE THREAD

**Issue by ivantcholakov** [fomantic/Fomantic-UI#1560]
I use webfontloader Javascript for loading font: https://github.com/typekit/webfontloader . In this case @font-face about icons is not needed to be included within the resulting css. There are variables like @importOutlineIcons and @importBrandIcons, it seems that they can be used to exclude @font-face definitions, but there is no variable such as @importIcons that could do the same for 'Icons' font. So, the original source needs to be touched, it seems to me inevitable, which is not good.

Could you add an option for removing @font-face about 'Icons' font?

**Comment by lubber-de** [comment]
So, you don't want the icons at all? Then adjust your `semantic.json` with the `components` parameter to only include the components you need and exclude the icons
See https://fomantic-ui.com/introduction/build-tools.html#semanticjson

**Comment by ivantcholakov** [comment]
No, I need icons, at the same time I need to exclude only this:

```less
@font-face {
  font-family: 'Icons';
  src: @fallbackSRC;
  src: @src;
  font-style: normal;
  font-weight: @normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```
The other definitions i.icon { ... } and etc. are needed. The mentioned JavaScript takes care about loading the corresponding font, and for for interaction with it I've made a separate CSS, it looks this way:

```css
@font-face {
    font-family: 'icons';
    src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.eot");
    src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.woff2") format('woff2'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.woff") format('woff'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.ttf") format('truetype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/icons.svg#icons") format('svg');
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-decoration: inherit;
    text-transform: none;
}

@font-face {
  font-family: 'outline-icons';
  src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.eot");
  src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.eot?#iefix") format('embedded-opentype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.woff2") format('woff2'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.woff") format('woff'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.ttf") format('truetype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/outline-icons.svg#icons") format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}

@font-face {
  font-family: 'brand-icons';
  src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.eot");
  src: url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.eot?#iefix") format('embedded-opentype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.woff2") format('woff2'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.woff") format('woff'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.ttf") format('truetype'), url("../composer-asset/fomantic/ui/src/themes/default/assets/fonts/brand-icons.svg#icons") format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```

I need @font-face for icons not to be within the compiled result.
