### ISSUE TITLE
[Feature Request] stackable action input

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#1579]
## Feature request
Taken from a discord suggestion a `stackable action input`, so the action button gets vertically attached on mobile devices

suggested codesnippet solution from discord
```css
@media (max-width: 767px) {
  .ui.action.input {
    flex-direction: column !important;
    input {
      width: 60px !important;
      text-align: center;
      border-right: 1px solid rgba(34,36,38,0.15) !important;
      border-bottom: none !important;
      border-top-right-radius: 4px !important;
      border-bottom-left-radius: 0px !important;
    }
    button {
      text-align: center !important;
      border-top-right-radius: 0px !important;
      border-bottom-left-radius: 4px !important;
      i {
        margin: 0 auto !important;
      }
    }
  }
}
```

### Before
![image](https://user-images.githubusercontent.com/18379884/87526308-fbc50100-c68a-11ea-86dc-8a2caa97f270.png)

### After
![image](https://user-images.githubusercontent.com/18379884/87526334-01bae200-c68b-11ea-80f6-5beefec131d1.png)
