### ISSUE TITLE
[modal] close button pops out of modal

### ISSUE THREAD

**Issue by silverwind** [fomantic/Fomantic-UI#1763]
## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/modal.html#full-screen
2. Open fullscreen modal example
3. Remove the `fullscreen` class on `modal` in DevTools

## Expected result
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/115237/99000099-0c9e5a00-2539-11eb-9c42-cacd6ee0bb65.png">

## Actual result
<img width="1181" alt="Screen Shot 2020-11-12 at 22 45 12" src="https://user-images.githubusercontent.com/115237/98999902-c5b06480-2538-11eb-814d-7feca6020628.png">

## Additional info

Not sure if this is a indented effect but it does not seem like it. Possible workaround:

```css
.ui.modal:not(.fullscreen):not(.basic) > .close {
  top: 1rem;
  right: 1rem;
  color: inherit;
}
```
