### ISSUE TITLE
[table] Hoverable rows

### ISSUE THREAD

**Issue by BLumia** [fomantic/Fomantic-UI#1994]
# Feature Request

Right now we have [Selectable Row](https://fomantic-ui.com/collections/table.html#selectable-row) in Fomantic-UI so we can have a table that can have its rows appear selectable. Since the semantic is selectable, the cursor is changed to `cursor: pointer;` to let the user know the row is selectable.

In some case, we just would like to highlight the current row that the cursor is on, but the whole row is not selectable (i.e. the row have a hover background but the cursor stays unchanged). Both [Bootstrap](https://getbootstrap.com/docs/4.4/content/tables/#hoverable-rows) and other frameworks like [Bulma](https://bulma.io/documentation/elements/table/#:~:text=You%20can%20add%20a-,hover%20effect,-on%20each%20row) have such feature built-in. So I guess it will be good if that can also be a built-in feature from Fomantic-UI.

I propose to introduce a `hoverable` variation for the table. It does what `selectable` does but without changing the cursor. So it could be easy to implement and convenient to use.

## Example (if possible)

https://jsfiddle.net/ao5prnuw/

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/10095765/123208335-7af4c300-d4f1-11eb-8cd1-eb2eff778082.png)

(basically the same with selectable but the cursor is not changed, check out the jsfiddle link for actual example)

**Comment by lubber-de** [comment]
Basically good idea.However, while looking at the current code, that would mean to double a lot of css selectors to make this happen by your proposed approach (there are a lot of variations which take care of a possible existing `selectable` class)


I see two options here:
#### 1. Rename `selectable` to `hoverable` and only if also `selectable` is added to the table, the pointer cursor appears

Pros
✔️  semantic naming seems logical

Cons
🚫  That would be a **huge** breaking change unfortunately 😢 

#### 2. Invent `hoverable` only to remove the pointer cursor for existing `selectable` tables

Pros
✔️ No breaking change
✔️Works with any existing FUI Version
✔️Works in every possible variation
✔️less additional css selectors

Cons
🚫 It's not really logically named IMHO.

See https://jsfiddle.net/lubber/ypr0q3kL/5/

#### Override to make it work in any FUI version available today
```css
.ui.table > tr > td.selectable,
.ui.table > tbody > tr > td.selectable,
.ui.selectable.table > tbody > tr,
.ui.selectable.table > tr {
    cursor: default;
}
.ui.table > tr > td.hoverable.selectable,
.ui.table > tbody > tr > td.hoverable.selectable,
.ui.hoverable.selectable.table > tbody > tr,
.ui.hoverable.selectable.table > tr {
	cursor: pointer;
}
```


#### Changes in current code for recompilation
```css
.ui.table > tr > td.selectable:not(.hoverable),
.ui.table > tbody > tr > td.selectable:not(.hoverable),
.ui.selectable.table:not(.hoverable) > tbody > tr,
.ui.selectable.table:not(.hoverable) > tr {
	cursor:pointer;
}
```
