### ISSUE TITLE
[form] Field description

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2222]
Thinking perhaps there should be a description class (or similar) that could be used within a form field class to provide a description (or instructions) of what to do with a field; where all the margins, etc, will look nicer. An example use case could be like having what minimum length a password should be above a password field

For example, if currently using a standard `<p>` tag:

![image](https://user-images.githubusercontent.com/1376843/152544979-837e8a48-ff39-4377-bd6a-bcb9e312d873.png)

Could possibly use `<small>` tag where the spacing is slightly better; but a bit small:

![image](https://user-images.githubusercontent.com/1376843/152545135-3cf572ba-8e61-473b-bd41-e41eb7205716.png)

I'm thinking a nicer solution could be similar as to how header and sub header work - nicer spacing with a slightly lighter font colour and not too far away from the form field

**Comment by prudho** [comment]
That's something doable with a few lines of codes:

In `src\definitions\collections\form.less` just add:
```less
.ui.form .field > label > div.description {
  font-size: @relativeMini;
  font-weight: @normal;
  color: @inputPlaceholderFocusColor;
  line-height: 1.2em;
}
```

Now a description can be added like this:
```html
<div class="field">
  <label>
    Name
    <div class="description">Some instructions here</div>
  </label>
  <input type="text" name="shipping[first-name]" placeholder="First Name">
</div>
```

Here's the result:
![image](https://user-images.githubusercontent.com/7557689/157061012-997bd9a4-f686-4e2e-8214-c89b4ad0e495.png)

But this will also trigger some issues:
- Grouped fields will not be aligned anymore:
![image](https://user-images.githubusercontent.com/7557689/157061248-fd601c5f-4aff-4a68-9f90-02dc56455f55.png)

- Inline fields will need a better vertical align:
![image](https://user-images.githubusercontent.com/7557689/157061648-58340a85-912d-464b-a905-28cf9a0e113f.png)
(`text-bottom` seem to be better than `baseline`)

For my apps, I prefer make use of tooltips to inform users:
```html
<div class="field">
  <label>
    Name
    <span data-tooltip="Some instructions here" data-variation="tiny" data-position="top left"><i class ="primary question circle outline icon"></i></span>
  </label>
  <input type="text" name="shipping[first-name]" placeholder="First Name">
</div>
```
![Animation](https://user-images.githubusercontent.com/7557689/157065583-4dafaa23-c86c-471b-aaea-4a3965dc6ac0.gif)

**Comment by jamessampford** [comment]
Though developers should pay attention to those scenarios (grouped and inline), it still could potentially be a useful addition

i like also like your alternative solution using a tooltip :)

**Comment by jamessampford** [comment]
Just adding the below as an alternative seen elsewhere as “help text”

![IMG_1437](https://user-images.githubusercontent.com/1376843/197411422-b7769af1-c5f7-453e-85e7-f1f578297f18.jpeg)

**Comment by prudho** [comment]
This help text seems less odd below than above, and don't mess grouped fields alignment.

![image](https://github.com/fomantic/Fomantic-UI/assets/7557689/35bb2ec4-b23a-4c9b-979a-28475d7b17a9)

Here's a quick writeup form implementing it, in `form.less`:
```less
/* --------------------
      Helper texts
--------------------- */

.ui.form .field > div.help.text,
.ui.form .field .ui.checkbox > div.help.text {
    font-size: @relativeSmall;
    font-weight: @normal;
    color: @inputPlaceholderFocusColor;
    line-height: 1.5em;
}
```

```html
<div class="field">
  <label>Name</label>
  <div class="two fields">
    <div class="field">
      <input type="text" name="shipping[first-name]" placeholder="First Name">
      <div class="help text">What's your name ?</div>
    </div>
    <div class="field">
      <input type="text" name="shipping[last-name]" placeholder="Last Name">
    </div>
  </div>
</div>
```

Inline is messy again, tho:
![image](https://github.com/fomantic/Fomantic-UI/assets/7557689/386c57ad-5f2c-407f-acad-d5ed5615503c)

Any thoughs ?
