### ISSUE TITLE
[dropdown] Let "multiple search selection" dropdowns work with descriptions

### ISSUE THREAD

**Issue by designosis** [fomantic/Fomantic-UI#2238]
# Feature Request

The [description](https://fomantic-ui.com/modules/dropdown.html#description) dropdown feature appears not to work with multiple search selection dropdowns. This combination would be amazing in terms of UX.

There is one problem: Unless there's a built-in way to ONLY show the text (not description), the "tags" of the multi-select could be way too long (see jsfiddle below). The `onChange: function(value, text) { $(this).dropdown('set text',$(text).filter('.text').text()); }` workaround used in regular dropdowns is great, but I'm guessing more complex for multi-selects.

## Example

https://jsfiddle.net/designosis/onq9b7km/

## Screenshot
![Screen Shot 2022-02-16 at 12 35 33 PM](https://user-images.githubusercontent.com/146623/154342207-f8563161-9207-4ee1-bae0-1515d3cab640.png)

**Comment by lubber-de** [comment]
You can solve this via CSS only.

```css
.ui.multiple.dropdown > .label > .description {
    display: none;  /* Use this to remove the description*/
    float: right;   /* Use this, to keep it, but move to the right just as in the selection list*/
}
```
You can also make the description look like a label detail by also adding the `detail` class to the item

See both examples here
https://jsfiddle.net/lubber/1j08w7fs/6/

![image](https://user-images.githubusercontent.com/18379884/212565377-b465c670-d3fc-40a7-903f-cf5554a00a07.png)
![image](https://user-images.githubusercontent.com/18379884/212565505-617dc20a-c5a1-4da3-b935-166923663101.png)


But, to avoid the script error: Whenever you have html inside your item, use an additional "data-value" attribute to your item, which is used for unique identification
