### ISSUE TITLE
[components] Add a reset for WordPress (admin)

### ISSUE THREAD

**Issue by grandeljay** [fomantic/Fomantic-UI#2277]
# Feature Request
I use fomantic for most of my WordPress plugins. It would be great to have an extra component `reset-wp` or similar I could include. Currently WordPress admin is not playing well with fomantic. Please see screenshot of the modal.

## Example
See screenshot

## Screenshot
![image](https://user-images.githubusercontent.com/45571053/159910035-81e4a27f-1102-421f-ad2c-9326678967aa.png)

**Comment by lubber-de** [comment]
Fomantic already has a [reset.css](https://github.com/fomantic/Fomantic-UI/blob/develop/src/themes/default/globals/reset.overrides) component which is based on [normalize.css](https://necolas.github.io/normalize.css/)
 I can only think of an additional theme for the reset component which would have extra reset classes for wordpress (admin)

I am no Wordpress expert and i dont have wordpress admin available or even time to investigate, so what exactly needs to be reset? 
Do you have a list of CSS Classes ? Or even better: The necessary reset code already available?

As fomantic already uses its own `ui` scope, i belive only the above mentioned normalize reset classes probably disturb here. In that case you could either compile FUI without the reset component or, if you use a CDN or local precompiled CSS: Use the single *.css files for each needed component, instead of the full semantic.css, and dont include reset.css. Probably solves your issue already.

**Comment by grandeljay** [comment]
> Fomantic already has a [reset.css](https://github.com/fomantic/Fomantic-UI/blob/develop/src/themes/default/globals/reset.overrides) component which is based on [normalize.css](https://necolas.github.io/normalize.css/)

I am already using the reset component on the above screenshot.

> so what exactly needs to be reset?

I also haven't done any investigation yet but noticed this the most prominently: 

```html
<button class="ui button approve">OK</button>
```

WordPress admin CSS applied to it
```css
.wp-core-ui button::-moz-focus-inner,
.wp-core-ui input[type="button"]::-moz-focus-inner,
.wp-core-ui input[type="reset"]::-moz-focus-inner,
.wp-core-ui input[type="submit"]::-moz-focus-inner {
	border-width: 0;
	border-style: none;
	padding: 0;
}

.wp-core-ui .button,
.wp-core-ui .button-secondary {
	color: #e14d43;
	border-color: #e14d43;
}

.wp-core-ui .button,
.wp-core-ui .button-secondary {
	color: #2271b1;
	border-color: #2271b1;
	background: #f6f7f7;
	vertical-align: top;
}

.wp-core-ui .button,
.wp-core-ui .button-primary,
.wp-core-ui .button-secondary {
	display: inline-block;
	text-decoration: none;
	font-size: 13px;
	line-height: 2.15384615;
	min-height: 30px;
	margin: 0;
	padding: 0 10px;
	cursor: pointer;
	border-width: 1px;
	border-style: solid;
	-webkit-appearance: none;
	border-radius: 3px;
	white-space: nowrap;
	box-sizing: border-box;
}
```

If you are willing to already set this up for me as a guideline I can try to complete it with the remaining CSS for other elements I encounter.

**Comment by lubber-de** [comment]
Resetting all of this (and probably even more) will be a mess of tons of !importants and extra css and i strongly believe many parts are missing.

Unfortunately wordpress is too generic here does not use a namespace on each component, but only on a parent object, so every fui component (button in this case) somewhere inside a nested `wp-core-ui` (which is probably set on body...) is affected.

I would rather adjust the wp css so they don't interfere with any fui css like this
```css
.wp-core-ui button:not(.ui)::-moz-focus-inner,
.wp-core-ui input[type="button"]:not(.ui)::-moz-focus-inner,
.wp-core-ui input[type="reset"]:not(.ui)::-moz-focus-inner,
.wp-core-ui input[type="submit"]:not(.ui)::-moz-focus-inner {
	border-width: 0;
	border-style: none;
	padding: 0;
}

.wp-core-ui .button:not(.ui),
.wp-core-ui .button-secondary {
	color: #e14d43;
	border-color: #e14d43;
}

.wp-core-ui .button:not(.ui),
.wp-core-ui .button-secondary {
	color: #2271b1;
	border-color: #2271b1;
	background: #f6f7f7;
	vertical-align: top;
}

.wp-core-ui .button:not(.ui),
.wp-core-ui .button-primary,
.wp-core-ui .button-secondary {
	display: inline-block;
	text-decoration: none;
	font-size: 13px;
	line-height: 2.15384615;
	min-height: 30px;
	margin: 0;
	padding: 0 10px;
	cursor: pointer;
	border-width: 1px;
	border-style: solid;
	-webkit-appearance: none;
	border-radius: 3px;
	white-space: nowrap;
	box-sizing: border-box;
}
```
