### ISSUE TITLE
[Breadcrumb] active section is not inline if larger then large size

### ISSUE THREAD

**Issue by juice** [fomantic/Fomantic-UI#2502]
# Bug Report
The active section is not inline if you use size big, huge, massive.

## Steps to reproduce
* https://fomantic-ui.com/collections/breadcrumb.html#size

## Expected result
The active section should stay inline even on larger sizes.

## Actual result
The active section does a line break with larger sizes.

## Screenshot (if possible)
<img width="657" alt="Screenshot 2022-10-15 at 17 43 25" src="https://user-images.githubusercontent.com/179705/195995392-f659a7cd-283b-402c-8362-42cdc43b1435.png">

## Version
2.9.0

**Comment by lubber-de** [comment]
🤔  I cannot reproduce this behavior until the available space does not fit. Then it's the intention do the line break.
![breadcrumbsizing](https://user-images.githubusercontent.com/18379884/196055027-cb10dbac-8279-4bfc-9187-b39b22daedb4.gif)

As your screenshot indeed would provide enough space: Could you tell more about your setup? Zoom level? Dpi settings? Video solution?

**Comment by juice** [comment]
@lubber-de Hi, thank you for checking. I just noticed that this is a Safari specific problem. Chrome works for me, but Safari does a line break since 2.9.0.

**Comment by lubber-de** [comment]
This seems to be a Safari Bug. It happens with some customs fonts and font-size > 1 and display: flex or display:inline-block, i found other projects dealing with similiar issues for example https://github.com/rsms/inter/issues/321

As a workaround you can try to set display: block or white-space:nowrap to such elements, but we have to deeply test all possible use cases of all components before daring to apply the following into the FUI core

```css
/* Safari 10.1+ Selector Hack taken from https://browserstrangeness.bitbucket.io/css_hacks.html#safari */
@media not all and (min-resolution:.001dpcm) {
  @media {
    .ui.breadcrumb {
      display: block;
/* OR */
      white-space: nowrap;
    }
  }
}
```
