### ISSUE TITLE
[statistic] horizontal statistics with icons/images

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2540]
# Bug Report
When a statistic has an icon/image, when using horizontal statistics, the icon/image will appear above the `value` instead of the expected left side

## Steps to reproduce
1. Copy the example at https://fomantic-ui.com/views/statistic.html#value
2. Add the horizontal class to the parent statistics node 

## Expected result
Icons/Images to be left of the value

## Actual result
Appear above the value

## Testcase
https://jsfiddle.net/5bq83w1r/

**Comment by lubber-de** [comment]
Maybe i misunderstood, but i cannot reproduce the issue, even when using your jsfiddle the icon/image is shown to the left as expected ?
![image](https://user-images.githubusercontent.com/18379884/199709352-e75e85da-254e-4ec1-ac40-30a0c21c5fec.png)

**Comment by jamessampford** [comment]
It seems that this may just happening on Safari on iPad

![IMG_1441](https://user-images.githubusercontent.com/1376843/199710158-14c2f69f-9f52-4555-bbb1-a7f76efeb97e.jpeg)

**Comment by lubber-de** [comment]
Confirmed 😢 Safari is going to be the next Internet Explorer...
It's the same Safari Bug as in #2502 

Workaround
```css
/* Safari 10.1+ Selector Hack taken from https://browserstrangeness.bitbucket.io/css_hacks.html#safari */
@media not all and (min-resolution:.001dpcm) {
  @media {
    .ui.horizontal.statistics .statistic,
    .ui.horizontal.statistic {
      white-space: nowrap;
    }
  }
}
```
