### ISSUE TITLE
[textarea] Textarea with action should be styled as close as possible as input

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2814]
# Feature Request

`textarea` is basically an `input` that support multiple lines. Therefore I expect the same features as for input. The css should be generated for input/textarea as much as possible using deduplicated code/less.

Currently there are at least there differences:

a) the width is not the same for the same markup (input has `width: auto`)

b) textarea border is not "unrounded" for right (probably for left too) action
   - and the action height should be probably limited to standard action height as with regular one-line input

## Repro

https://jsfiddle.net/vhfrb2qt/1/

## Screenshot (if possible)

![image](https://github.com/fomantic/Fomantic-UI/assets/2228672/dd0dbbab-307d-465e-9cb3-c591ef6d8d10)

**Comment by ko2in** [comment]
Limiting action height next to textarea is not a good idea. The reason of action input is to stack together, so they should align equally.
![textarea-with-action](https://github.com/fomantic/Fomantic-UI/assets/930315/d9aca780-ed90-48aa-a594-42b91a91f159)

**Comment by lubber-de** [comment]
I think, he meant a min height of the textarea so it matches the normal button height at least.
We could add something like
````less

@actionInputMinHeight: @iconWidth: (@verticalPadding * 2) + @lineHeight;

.ui.action.button > textarea {
/* 2x button padding (top+bottom) + line-height (1.4em)*/
  min-height: @actionInputMinHeight;  /**-> something around 3em in summary */
}
```
https://jsfiddle.net/lubber/6a5gjmez/5/

if we now also add something to match the width of textare to an input, we whole feature request is fullfilled
