### ISSUE TITLE
[font] Multiple font support

### ISSUE THREAD

**Issue by TivoSoho** [fomantic/Fomantic-UI#2892]
# Feature Request

Currently FUI supports one font, by default Lato. However would be great if it supported multiple without having to resort to some "gymnastics". Our main case - page font and header font are different.

**Comment by lubber-de** [comment]
FUI supports as many fonts as you need, not only one.
There are many usable LESS variables to easily achive what you need via a custom theme's `site.variables`

You dont need to change everything below, it always depends on your needs and you only need to adjust the variables
This is intended flexibility and goes as easy or complex as you want it 😉 

```less 
// file: site.variables
// global font name(s)
@fontName: 'myGlobalFontName';

// your desired Header font
@headerFont: 'myHeaderFontAsINeed';

// your desired page Font
@pageFont: 'myPageFontAsIWantIt';

// declare your own custom font-face definitions to be imported (by default the list just uses the `@fontname`, thats why you probably think FUI uses only 1 font

// you can declare as much fonts and as much properties you need for a font-face definition
@fonts: {
    @myGlobalFont: {
        font-family: @fontName;
        src: url("@{fontPath}/@{fontName}.woff2") format("woff2");
        font-style: normal;
        font-weight: normal;
    };
    @myHeaderFont: {
        font-family: @headerFont;
        src: url("@{fontPath}/@{headerFont}.woff2") format("woff2");
        font-style: normal;
        font-weight: normal;
    };
    @myPageFont: {
        font-family: @pageFont;
        src: url("@{fontPath}/@{pageFont}.woff2") format("woff2");
        font-style: normal;
        font-weight: normal;
    };
    @myPopupFont: {
        font-family: 'myPopupFont';
        src: url("@{fontPath}/@myPopupFont.woff2") format("woff2");
        font-style: normal;
        font-weight: normal;
    };

};

// this way you can use whatever font you like also in each component separately if needed

// have a different headerfont in the popup module only
// file: popup.variables
@headerFont: 'myPopupFont';
```
