### ISSUE TITLE
[Bulleted list] Grid inside bulleted list

### ISSUE THREAD

**Issue by ghabriel25** [fomantic/Fomantic-UI#2950]
Note: on smartphone atm.

It seems bulleted list (dot) moved up a little when there is a grid inside item

```
<div class="ui very relaxed large bulleted list">
    <div class="item">
        <div class="ui middle aligned grid">
            <div class="fourteen wide column">
                <a href="#">Link 1</a>
            </div>
            <div class="two wide right aligned column">
                <a href="#" class="ui icon circular button>
                    <i class="x icon"></i>
                </a>
            </div>
        </div>
    </div>
</div>
```

**Comment by lubber-de** [comment]
Basically a bulleted list was not designed for your  very specific use case and infact there are many possibilities and ideas where to adjust the bullet points.

See here for a possible adjustment of a `bulleted` or `ordered` list containing items which themselves contain a `grid`, a `celled grid` or a `message`. There might be endless other use cases where the bullet point would need personal desired adjustments.

https://jsfiddle.net/lubber/k74srLqv/20/

```css
.ui.list:where(.bulleted,.ordered) > .item:has( > .grid)::before {
  top: 1.5em;
}
.ui.list:where(.bulleted,.ordered) > .item:has( > .celled.grid)::before {
  top: 3.25em;
}
.ui.list:where(.bulleted,.ordered) > .item:has( > .message)::before {
  top: 2em;
}
```
As the CSS is so specific (and i also used pseudo elements which are only supported in very modern browsers), we cannot fix this in the FUI core to satisfy every situation. Feel free to take the above code and adjust it to your needs as custom CSS in your own application
