### ISSUE TITLE
[Scrollbar] CSS style for Firefox scrollbar break the scrollbar on chromium browser (Chrome/ Edge) 

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#3002]
# Bug Report

For some reason when I update to the new version of the these browser:
    Chrome: v121.0.6167.184 (Official Build) (64-bit)
    Edge: v121.0.2277.112 (Official build) (64-bit)
Custom scrollbar break and use default scrollbar instead.

See image below:

## Screenshot (if possible)
![err](https://github.com/fomantic/Fomantic-UI/assets/28552977/9c6b4a2b-0452-4f5b-b4ff-9dfeeb5c5e25)

As you can see when I turn off ``scrollbar-color: rgba(0, 0, 0, 0.25) rgba(0, 0, 0, 0.1);`` and ``scrollbar-width: thin;``, the custom scrollbar displayed, but keeping those CSS will break the custom scrollbar.

Library source code where the bug is present:
https://github.com/fomantic/Fomantic-UI/blob/6daf34d16395f8aa9b964719095c775fc8e4e95b/dist/semantic.css#L664-L673
```css
body .ui {
  /* IE11 */
  scrollbar-face-color: #bfbfbf;
  scrollbar-shadow-color: #bfbfbf;
  scrollbar-track-color: #e6e6e6;
  scrollbar-arrow-color: #e6e6e6;
  /* firefox: first color thumb, second track */
  scrollbar-color: rgba(0, 0, 0, 0.25) rgba(0, 0, 0, 0.1);
  scrollbar-width: thin;
}
```

My temporary solution:
```CSS
body .ui {
    /* Override scrollbar-color */
    scrollbar-color: auto; /* Use browser default colors */
    /* Override scrollbar-width */
    scrollbar-width: auto; /* Use browser default width */
}
```

## Version

v2.9.3
