### ISSUE TITLE
Header no longer has rounded corners (regression)

### ISSUE THREAD

**Issue by romaninsh** [fomantic/Fomantic-UI#308]
# Bug Report

After switching our project from Semantic to Fomantic, we noticed that dialog top edges are no longer rounded. After some digging we noticed that "header" had rounded corners before, but it is no longer the case:

``` css
/*******************************
             Modal
*******************************/

.ui.modal > :first-child:not(.icon),
.ui.modal > .icon:first-child + * {
  border-top-left-radius: 0.28571429rem;
  border-top-right-radius: 0.28571429rem;
}
```

Image before:
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/453929/50095215-e5d02f80-020c-11e9-9ac5-5199d50dc4d0.png">

And after:
<img width="1605" alt="image" src="https://user-images.githubusercontent.com/453929/50095229-f1bbf180-020c-11e9-898e-37ee181db246.png">

This affects all the dialogs.

## Steps to reproduce
1. TBA
2.
3.

## Testcase
http://ui.agiletoolkit.org/demos/modal2.php

## Version
2.6.4
