### ISSUE TITLE
[Dropdown] Incorrect display of remote dropdown 

### ISSUE THREAD

**Issue by dabroz** [fomantic/Fomantic-UI#3087]
# Bug Report

This is visible even in Fomantic UI docs. I can also reproduce this locally.

## Steps to reproduce
1. Visit https://fomantic-ui.com/modules/dropdown.html#match-search-query-on-server
2. Try searching for "linux"

## Expected result

The results should not be mangled

## Actual result

Results are displayed incorrectly

## Testcase

-

## Screenshot (when possible)

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/6eb4731e-3da0-4e6e-9b35-2d603a8dee04">

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/62ea2bbc-c7f9-48a0-9c57-5345aadaa0c0">

## Version

2.9 (as per fomantic-ui.com website)

**Comment by dabroz** [comment]
And this is how it looks in my project after selecting a value

<img width="682" alt="image" src="https://github.com/user-attachments/assets/e5541e08-4918-431b-a107-7f04db9fb05c">

**Comment by lubber-de** [comment]
Thanks for reporting. While i test a fix for all possible situations and dropdown variants, please try to add the following to your project

```css
.ui.selection.dropdown .menu > .item:has( > .description) {
  display: flex;
  flex-direction: row-reverse;
  justify-content: space-between;
}
```

**Comment by dabroz** [comment]
Thanks for looking into it!

However, this doesn't seem to solve this issue. Without this patch:
<img width="666" alt="image" src="https://github.com/user-attachments/assets/34eb6650-6650-4f6e-a659-4a480a9507b9">
<img width="679" alt="image" src="https://github.com/user-attachments/assets/b07d919d-ebba-47b9-b9f3-f926938d10e4">

With this patch:
<img width="664" alt="image" src="https://github.com/user-attachments/assets/9c888c36-541b-4307-b1fa-d87f07e287fa">
<img width="682" alt="image" src="https://github.com/user-attachments/assets/7bf99184-92bd-4589-bcce-816479f8bace">

**Comment by lubber-de** [comment]
@dabroz Please try to enhance the selector as follows, so the selected text matches the dropdown item list.
```css
.ui.selection.dropdown > .text:not(.default):has( > .description),
.ui.selection.dropdown .menu > .item:has( > .description) {
  display: flex;
  flex-direction: row-reverse;
  justify-content: space-between;
}
```
However, it seems you removed the left margin from the description using custom css(?) .
