### ISSUE TITLE
[modal] left actions

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#3180]
# Feature Request

Niche use, but I thought I'd suggest it. I'd like to be able to add a left-positioned button to a modal as an extra action that doesn't mean approve/deny/cancel. 

To get this I added some css and custom structure to the dom:
```css
.ui.modal>.actions>.left {
  position: absolute;
  left: 1rem;
  & .icon {
    margin: 0 .42857143em 0 -.21428571em !important;
  }
}
```
```html
<div class="ui small modal">
  <div class="ui header">Modal</div>
  <div class="content">
    Wow!
  </div>
  <div class="actions">
    <span class="left">
      <a class="ui ok blue button" data-action="do-thing">
        <i class="smile icon"></i>
        Do Thing
      </a> 
    </span>
    <a class="ui cancel button">Cancel</a>
    <a class="ui positive button"><i class="check icon"></i>k</a>
  </div>
</div>
```

I use a custom callback to check for any `data-action` attributes to make sure I call the right code:
```js
onApprove: $el => {
    let action = $el.data("action");
    if(action) {
        alert(`${action}'d!`);
        return false;
    }
}
```

## Example 

https://jsfiddle.net/xd40coas/

## Screenshot 
![Image](https://github.com/user-attachments/assets/c7c8570e-8bef-4af3-97a2-49a146765d4d)
