### ISSUE TITLE
Reduce semantic ui to bare minimum

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#402]
Hi,

I am using "gulp build" to build semantic ui to the only really necessary code. However, after opening the generated "semantic.css" file I see there is lots of improvements that could be made. Maybe some of the ones I pointed below are already possible, so please excuse me and explain me how to proceed.

1) COLORS. Many times on my projects I use only blue/green/basic/inverted colors. So I wouldnt need that many color options inside my "semantic.css" file. Is it possible to set in the "semantic.json" file only the colors I will use?

2) BUTTONS. I dont really need "animated" buttons, "labeled" buttons, "social" buttons, "tertiary" buttons, "two, three, four..." buttons... Can I only have the option to use the most basic form of button (no icon, just text) but still being able to use the nice design of semantic?

3) SIZE. Sometimes I just use the "medium" and "small" in my entire projects. Is it really needed to import all the 8 sizes? I am not complaining about these size options, it's good and adds granularity control over the project. But sometimes I really only need 2 button sizes and nothing else.

**People are talking so much on other threads regarding the dependecy or not of jquery in FOMANTIC UI, but devs should be really looking into adding more control of what users will have to download on their browsers to use FOMANTIC. There is no point removing jquery dependency (which only adds a few KBs gziped) while colors, sizes, buttons... add hundreds of KBs gziped.**

**Comment by ColinFrick** [comment]
We added controls of the included colors with 2.7.0:
https://fomantic-ui.com/introduction/new.html#colors

Please keep the jQuery discussion in #374

**Comment by batata004** [comment]
Thanks! According to the documentation (in the link provided by you) I cant find the globals/colors.less file at https://github.com/fomantic/Fomantic-UI/tree/master/src/definitions/globals

I just want to know how do I specificy only some colors at `site.variables` to allow gulp to exclude all other colors.

Sorry about the jquery discussion here.

**Comment by lubber-de** [comment]
@batata004 
#### Regarding the different variants of elements like buttons
  We keep that in mind then designing the website to select and build only the components (and perhaps also only variants of those) you want. This of course would need to restructure all LESS files to accomplish this, so thanks for the idea, but it will take a while, i guess also as a second step.

#### Regarding colors
 It's actually https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/globals/colors.less
To remove colors you don't want, just remove each block starting with `@` and the colorname from the `@colors` mixin

You don't need to change anything in `site.variables`, just keep everything. Colors, you dont want, won`t get compiled into the final css file, It's the final css-file that counts.

For example: If you only want to keep blue and green, remove everyting else, so it results in
```less
@colors: {
  @blue: {
    color          : @blue;
    light          : @lightBlue;
    border         : @blueBorderColor;
    background     : @blueBackground;
    header         : @blueHeaderColor;
    boxShadow      : @blueBoxShadow;
    boxFloatShadow : @blueBoxFloatingShadow;
    text           : @blueTextColor;
    lightText      : @lightBlueTextColor;
    hoverText      : @blueHoverTextColor;
    focus          : @blueFocus;
    lightFocus     : @lightBlueFocus;
    down           : @blueDown;
    lightDown      : @lightBlueDown;
    active         : @blueActive;
    lightActive    : @lightBlueActive;
    shadow         : @blueTextShadow;
    lightShadow    : @lightBlueTextShadow;
    hover          : @blueHover;
    lightHover     : @lightBlueHover;
    ribbon         : @blueRibbonShadow;
    invertedRibbon : @blueInvertedRibbonShadow;
    isDark         : false;
    isVeryDark     : false;
  };
  @green: {
    color          : @green;
    light          : @lightGreen;
    border         : @greenBorderColor;
    background     : @greenBackground;
    header         : @greenHeaderColor;
    boxShadow      : @greenBoxShadow;
    boxFloatShadow : @greenBoxFloatingShadow;
    text           : @greenTextColor;
    lightText      : @lightGreenTextColor;
    hoverText      : @greenHoverTextColor;
    focus          : @greenFocus;
    lightFocus     : @lightGreenFocus;
    down           : @greenDown;
    lightDown      : @lightGreenDown;
    active         : @greenActive;
    lightActive    : @lightGreenActive;
    shadow         : @greenTextShadow;
    lightShadow    : @lightGreenTextShadow;
    hover          : @greenHover;
    lightHover     : @lightGreenHover;
    ribbon         : @greenRibbonShadow;
    invertedRibbon : @greenInvertedRibbonShadow;
    isDark         : false;
    isVeryDark     : false;
  };  
}
```
