### ISSUE TITLE
Add padding to checkbox input when necessary inside form fields

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#578]
# Feature Request

## Description
Sometimes I like to have checkboxes inside `.ui.form>.fields>.field` layouts, but currently it has no padding and puts the checkbox at the top of the field. I think it should pad the checkbox's top so it lines up with the inputs better.

## Example
I used the following CSS to make it look better:
```css
.ui.form .fields .field:not(:only-child) .ui.checkbox {
  margin-top: 2.25em;
}
.ui.form .fields .field:not(:only-child) .ui.toggle.checkbox {
  margin-top: 2.15em;
}
.ui.form .fields .field:not(:only-child) .ui.slider.checkbox {
  margin-top: 1.35em;
}
```

The `:not(:only-child)` selector ensures that the checkbox will not have the extra padding if it is the only `field` in the `fields` div.

## Testcase
https://jsfiddle.net/bha06ugz/

## Screenshot
![image](https://user-images.githubusercontent.com/7832163/54849737-c2ed6580-4caa-11e9-9960-823ccc22d153.png)
