### ISSUE TITLE
Table Spacer

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#592]
# Feature Request

## Description
The ability to set table rows or cells as "spacer" elements to hide cell

## Example
Here's some CSS I threw together for a demo:
```css
table.ui.table tr td::after,
table.ui.table tr.spacer td.spacer::after {
  content: "&nbsp;";
  visibility: hidden;
}

table.ui.table tr.spacer td {
  border-left: none;
  border-right: none;
}

table.ui.table tr td.spacer {
  content: '&nbsp;';
  border-left: none;
  border-bottom: none;
}
```

## Testcase (when possible)
https://jsfiddle.net/rap0ho71/4/

## Screenshot
![image](https://user-images.githubusercontent.com/7832163/55098511-88f1da00-5083-11e9-87e4-eaedd73709ea.png)

## Notes
I don't think it would play very well with the sortable tables
