### ISSUE TITLE
[Progress] Javascript-free variant

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#813]
# Feature Request

## Description
I think it would be nice to have a variant of the progress bar that doesn't require javascript to only need a static bar to show status.

## Example
In my demo, I had to add a `style` attribute to the bar with a variable since the [`attr`](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) function doesn't support numbers. I also had to give the progress bar an empty `data-percent` attribute, if it wasn't there the bar wasn't visible. With a slight rule change it wouldn't be necessary.

For example, here's two bars:

```html
<div class="ui teal progress">
  <div class="bar" style="--percent:74%"></div>
  <div class="label">74% Funded</div>
</div>
```

In order to get this to work, you have to change one rule regarding the progress bar:

```css
.ui.ui.ui.progress:not([data-percent]) .bar:not([style*="--percent"]), .ui.ui.ui.progress[data-percent="0"] .bar:not([style*="--percent"]) {
    background: transparent;
}
```

And add the following:
```css
.ui.progress:not([data-percent]) > .bar[style*="--percent"] {
    width: calc(var(--percent));
}
```

## Testcase
https://jsfiddle.net/pgnzmv8h/4/

## Screenshot
![image](https://user-images.githubusercontent.com/7832163/59454416-3d6fe200-8dcf-11e9-8843-ef4a7d6697bb.png)
It's just a regular progress bar without the animations, really
